# Forked from https://github.com/yeasy/docker-hyperledger-membersrvc:latest

# Dockerfile for Hyperledger membersrvc image. This actually follow hyperledger
# image but to make sure the config is done.
# Data is stored under /var/hyperledger/db and /var/hyperledger/production

FROM stylix/hyperledger:latest
MAINTAINER Siriwat K.

CMD ["membersrvc"]